// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package main

import (
	"time"
)

type AccountInput struct {
	Name string `json:"name"`
}

type Mutation struct {
}

type Order struct {
	ID         string           `json:"id"`
	CreatedAt  time.Time        `json:"createdAt"`
	TotalPrice float64          `json:"totalPrice"`
	Products   []*OrderProducts `json:"products"`
}

type OrderInput struct {
	AccountID string                `json:"accountId"`
	Products  []*OrderProductsInput `json:"products"`
}

type OrderProducts struct {
	ID           string  `json:"id"`
	Name         string  `json:"name"`
	Descripition string  `json:"descripition"`
	Price        float64 `json:"price"`
	Quantity     int     `json:"quantity"`
}

type OrderProductsInput struct {
	ID       string `json:"id"`
	Quantity int    `json:"quantity"`
}

type PaginatioInput struct {
	Skip *int `json:"skip,omitempty"`
	Take *int `json:"take,omitempty"`
}

type Product struct {
	ID           string  `json:"id"`
	Nmae         string  `json:"nmae"`
	Descripition string  `json:"descripition"`
	Price        float64 `json:"price"`
}

type ProductInput struct {
	Name         string  `json:"name"`
	Descripition string  `json:"descripition"`
	Price        float64 `json:"price"`
}

type Quary struct {
	Accounts []*Account `json:"accounts"`
	Products []*Product `json:"products"`
}

type Query struct {
}
